"""
vlm_client.py — Ollama VLM client for customer demographic analysis.

Sends two images to the vision-language model (default: qwen2.5vl:7b):
  1. FULL_FRAME_IMAGE: Complete CCTV frame for scene context.
  2. PERSON_CROP_IMAGE: Cropped target person image for focused analysis.

Parsed JSON response fields:
  {
      "track_id": "<TRACK_ID>",
      "analysis": {
          "age_estimate": 30,
          "age_range": "25-35",
          "apparent_gender": "male",
          "visibility": "clear",
          "confidence": 0.85
      }
  }
"""

import os
import json
import re
import base64
import time
from pathlib import Path
from typing import Optional, Union

import cv2
import requests

try:
    import ollama
    HAS_OLLAMA = True
except ImportError:
    ollama = None
    HAS_OLLAMA = False

OLLAMA_API_URL = os.environ.get("OLLAMA_API_URL", "http://localhost:11434").rstrip("/")

try:
    from retail_analytics.utils import setup_logger
except ImportError:
    from utils import setup_logger

logger = setup_logger()

# ---------------------------------------------------------------------------
# Default configuration
# ---------------------------------------------------------------------------

DEFAULT_VLM_MODEL = "qwen2.5vl:7b"

# ---------------------------------------------------------------------------
# VLM Prompt Template
# ---------------------------------------------------------------------------

VLM_PROMPT_TEMPLATE = """You are an AI vision analyst working with a CCTV retail analytics system.

You will receive:
1. FULL_FRAME_IMAGE (first image):
   - The complete CCTV camera frame.
   - Used only for context and verifying that the person crop belongs to the correct individual.

2. PERSON_CROP_IMAGE (second image):
   - A cropped image of ONE tracked person extracted by an object detector.
   - This is the primary image for analysis.

3. TRACK_ID:
   - A unique tracking identifier generated by the tracking system: {track_id}
   - You must preserve this ID in your response.

Your task:
Analyze ONLY the person in PERSON_CROP_IMAGE.

Estimate:

1. Apparent gender:
   - male
   - female
   - uncertain

2. Age:
   - Estimate numerical age.
   - Provide an age range.

3. Person visibility:
   - clear: face/body is sufficiently visible
   - partial: some parts are hidden or unclear
   - poor: insufficient information

4. Confidence score:
   - A value between 0.0 and 1.0 representing your confidence.

Analysis rules:

- Do NOT identify the person.
- Do NOT infer name, ethnicity, religion, occupation, or personal background.
- Do NOT use other people in FULL_FRAME_IMAGE to estimate this person's age or gender.
- Do NOT change or create a new TRACK_ID.
- Do NOT combine multiple people.
- Analyze only the person corresponding to the provided crop.
- If the face is not visible, reduce confidence.
- If the image quality is poor, blurry, dark, or occluded, return uncertain instead of guessing.
- Use facial features, body proportions, and visible physical characteristics only.
- Clothing style, accessories, and location in the store should not be used as primary evidence.

Important:
Age estimation is approximate.
Apparent gender classification can be uncertain.
Return the most likely estimate with confidence.

Return ONLY valid JSON.

Output format:

{{
    "track_id": "{track_id}",
    "analysis": {{
        "age_estimate": 30,
        "age_range": "25-35",
        "apparent_gender": "male",
        "visibility": "clear",
        "confidence": 0.85
    }}
}}

Before answering:
1. Check PERSON_CROP_IMAGE.
2. Verify it matches the person in FULL_FRAME_IMAGE.
3. Analyze the person.
4. Return JSON only."""


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _extract_json_block(text: str) -> str:
    """
    Robustly extract the JSON object from a model response that may contain
    markdown code fences, whitespace, or trailing commentary.
    """
    text = text.strip()

    # 1. Try markdown code block  ```json ... ```  or  ``` ... ```
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text)
    if match:
        return match.group(1).strip()

    # 2. Find the outermost { … }
    first = text.find("{")
    last  = text.rfind("}")
    if first != -1 and last != -1 and last > first:
        return text[first : last + 1].strip()

    return text


def _encode_image_b64(path: str, max_dim: Optional[int] = None) -> str:
    """Read an image file and return its base64-encoded bytes, optionally downscaling to max_dim."""
    if max_dim is not None:
        try:
            img = cv2.imread(path)
            if img is not None:
                h, w = img.shape[:2]
                if max(h, w) > max_dim:
                    scale = max_dim / float(max(h, w))
                    nw, nh = int(w * scale), int(h * scale)
                    img = cv2.resize(img, (nw, nh), interpolation=cv2.INTER_AREA)
                success, buf = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, 85])
                if success:
                    return base64.b64encode(buf).decode("utf-8")
        except Exception:
            pass
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


# ---------------------------------------------------------------------------
# VLMClient class
# ---------------------------------------------------------------------------

class VLMClient:
    """
    Wraps the Ollama API to send two images (full frame + person crop) and
    parse the model's demographic JSON response.
    """

    def __init__(
        self,
        model: str = DEFAULT_VLM_MODEL,
        temperature: float = 0.05,
        retries: int = 2,
        retry_delay: float = 2.0,
        api_url: str = OLLAMA_API_URL,
    ):
        self.model       = model
        self.temperature = temperature
        self.retries     = retries
        self.retry_delay = retry_delay
        self.api_url     = api_url.rstrip("/")
        logger.info(f"[VLMClient] Initialized with model='{model}', endpoint='{self.api_url}'")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        full_frame_path: str,
        crop_path: str,
        track_id: int,
    ) -> Optional[dict]:
        """
        Send FULL_FRAME_IMAGE and PERSON_CROP_IMAGE to the VLM.

        Args:
            full_frame_path: Path to the complete CCTV frame image.
            crop_path:       Path to the cropped image of the tracked person.
            track_id:        Unique tracking ID.

        Returns:
            Dict containing normalized analysis fields.
        """
        if not Path(full_frame_path).exists():
            logger.error(f"[VLMClient] Full frame not found: {full_frame_path}")
            return self._fallback_result(track_id, "full frame not found")

        if not Path(crop_path).exists():
            logger.error(f"[VLMClient] Crop not found: {crop_path}")
            return self._fallback_result(track_id, "crop not found")

        for attempt in range(1, self.retries + 2):
            logger.info(
                f"[VLMClient] Analyzing track {track_id} with model '{self.model}' "
                f"(attempt {attempt})..."
            )
            try:
                result = self._call_ollama(full_frame_path, crop_path, track_id)
                logger.info(
                    f"[VLMClient] Track {track_id} -> "
                    f"age={result.get('age_estimate')} ({result.get('age_range')}), "
                    f"gender={result.get('apparent_gender')}, "
                    f"vis={result.get('visibility')}, "
                    f"conf={result.get('confidence')}"
                )
                return result

            except Exception as exc:
                exc_str = str(exc)
                if "exceed_context_size" in exc_str or "context size" in exc_str.lower():
                    logger.error(f"[VLMClient] Track {track_id}: context overflow.")
                    break
                logger.warning(f"[VLMClient] Attempt {attempt} failed for track {track_id}: {exc}")
                if attempt <= self.retries:
                    time.sleep(self.retry_delay)
                else:
                    logger.error(f"[VLMClient] All attempts failed for track {track_id}.")

        return self._fallback_result(track_id, "max retries exceeded")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _call_ollama(self, full_frame_path: str, crop_path: str, track_id: int) -> dict:
        """
        Execute Ollama API call with full frame and person crop.
        Uses native ollama package if installed, otherwise communicates directly
        via HTTP REST requests to Ollama API.
        """
        prompt = VLM_PROMPT_TEMPLATE.format(track_id=track_id)
        raw_text = ""

        if HAS_OLLAMA and ollama is not None:
            try:
                response = ollama.chat(
                    model=self.model,
                    messages=[
                        {
                            "role": "user",
                            "content": prompt,
                            "images": [
                                str(Path(full_frame_path).resolve()),
                                str(Path(crop_path).resolve()),
                            ],
                        }
                    ],
                    options={
                        "temperature": self.temperature,
                        "top_p": 0.9,
                        "num_ctx": 4096,
                    },
                )
                raw_text = response.message.content or ""
            except Exception as exc:
                logger.debug(f"[VLMClient] ollama SDK call failed, falling back to HTTP REST: {exc}")
                raw_text = ""

        if not raw_text:
            # Full frame is optimized to max 960px for context (saves ~65% vision tokens),
            # while person crop is kept at 100% native resolution for face/body precision.
            full_b64 = _encode_image_b64(full_frame_path, max_dim=960)
            crop_b64 = _encode_image_b64(crop_path, max_dim=None)

            payload = {
                "model": self.model,
                "messages": [
                    {
                        "role": "user",
                        "content": prompt,
                        "images": [full_b64, crop_b64],
                    }
                ],
                "options": {
                    "temperature": self.temperature,
                    "top_p": 0.9,
                    "num_ctx": 4096,
                },
                "stream": False,
            }
            resp = requests.post(
                f"{self.api_url}/api/chat",
                json=payload,
                timeout=90,
            )
            resp.raise_for_status()
            data = resp.json()
            raw_text = data.get("message", {}).get("content", "")

        if not raw_text.strip():
            raise ValueError("VLM returned an empty response.")

        json_str = _extract_json_block(raw_text)
        if not json_str.strip():
            raise ValueError(f"Could not extract JSON from VLM response: {raw_text[:200]!r}")

        parsed = json.loads(json_str)
        return self._normalise(parsed, track_id)

    def _normalise(self, raw: dict, track_id: int) -> dict:
        """
        Normalise VLM output to guarantee structure and valid types.
        """
        analysis = raw.get("analysis", {})
        if not isinstance(analysis, dict):
            analysis = raw

        # Age estimate (int or None)
        age_estimate = analysis.get("age_estimate")
        if age_estimate is not None:
            try:
                if isinstance(age_estimate, str):
                    m = re.search(r"\d+", age_estimate)
                    age_estimate = int(m.group(0)) if m else None
                else:
                    age_estimate = int(age_estimate)
            except Exception:
                age_estimate = None

        # Age range (str)
        age_range = str(analysis.get("age_range", "")).strip()
        if not age_range and age_estimate:
            age_range = f"{max(0, age_estimate - 5)}-{age_estimate + 5}"

        # Apparent gender: male | female | uncertain
        gender_raw = str(
            analysis.get("apparent_gender", analysis.get("gender", "uncertain"))
        ).strip().lower()

        if "female" in gender_raw:
            apparent_gender = "female"
        elif "male" in gender_raw:
            apparent_gender = "male"
        else:
            apparent_gender = "uncertain"

        # Visibility: clear | partial | poor
        vis_raw = str(analysis.get("visibility", "clear")).strip().lower()
        if "poor" in vis_raw:
            visibility = "poor"
        elif "part" in vis_raw:
            visibility = "partial"
        else:
            visibility = "clear"

        # Confidence: float in [0.0, 1.0]
        conf_raw = analysis.get("confidence", 0.8)
        try:
            confidence = float(conf_raw)
            if confidence > 1.0 and confidence <= 100.0:
                confidence = confidence / 100.0
            confidence = max(0.0, min(1.0, confidence))
        except Exception:
            confidence = 0.5

        # Determine age_group
        range_lower = age_range.lower()
        if "child" in range_lower:
            age_group = "Child"
        elif "teen" in range_lower:
            age_group = "Teenager"
        elif "young adult" in range_lower:
            age_group = "Young Adult"
        elif "senior" in range_lower or "elder" in range_lower:
            age_group = "Senior"
        else:
            age = age_estimate
            if age is None and age_range:
                nums = [int(n) for n in re.findall(r"\d+", age_range)]
                if nums:
                    age = sum(nums) // len(nums)

            if age is not None:
                if age <= 12:
                    age_group = "Child"
                elif age <= 17:
                    age_group = "Teenager"
                elif age <= 25:
                    age_group = "Young Adult"
                elif age <= 30:
                    age_group = "Adult"
                elif age <= 55:
                    age_group = "Senior"
            else:
                age_group = "Adult"

        # Categorical confidence for terminal output
        if isinstance(confidence, (int, float)):
            conf_label = "High" if confidence >= 0.75 else ("Medium" if confidence >= 0.45 else "Low")
        else:
            conf_label = str(confidence).title()

        return {
            "track_id": track_id,
            "age_group": age_group,
            "gender": apparent_gender.title() if apparent_gender != "uncertain" else "Uncertain",
            "confidence": conf_label,
            "confidence_score": round(confidence, 2) if isinstance(confidence, (int, float)) else confidence,
            "age_estimate": age_estimate,
            "age_range": age_range or "Unknown",
            "apparent_gender": apparent_gender,
            "visibility": visibility,
            "analysis": {
                "age_group": age_group,
                "age_estimate": age_estimate,
                "age_range": age_range or "Unknown",
                "apparent_gender": apparent_gender,
                "visibility": visibility,
                "confidence": conf_label,
            }
        }

    @staticmethod
    def _fallback_result(track_id: int, reason: str) -> dict:
        """Return a sentinel result dict when the VLM call cannot succeed."""
        logger.warning(f"[VLMClient] Using fallback result for track {track_id} — reason: {reason}")
        return {
            "track_id": track_id,
            "age_estimate": None,
            "age_range": "Unknown",
            "age_group": "Unknown",
            "apparent_gender": "uncertain",
            "gender": "Uncertain",
            "visibility": "poor",
            "confidence": 0.0,
            "analysis": {
                "age_estimate": None,
                "age_range": "Unknown",
                "apparent_gender": "uncertain",
                "visibility": "poor",
                "confidence": 0.0,
            }
        }
